=== FreeCAD/FreeCAD/src/Tools/generateBase/generateMetaModel_Module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GenerateModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="PythonExport" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Documentation" minOccurs="0"/>
							<xs:element name="Methode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation"/>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="Const" type="xs:boolean" use="optional"/>
									<xs:attribute name="Keyword" type="xs:boolean" use="optional" default="false"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Attribute" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation"/>
										<xs:element ref="Parameter"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="ReadOnly" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Sequence" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="sq_length" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_concat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_repeat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_item" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_slice" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_ass_item" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_ass_slice" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_contains" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_inplace_concat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_inplace_repeat" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="CustomAttributes" minOccurs="0"/>
							<xs:element name="ClassDeclarations" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Include" type="xs:string" use="required"/>
						<xs:attribute name="Father" type="xs:string" use="required"/>
						<xs:attribute name="Twin" type="xs:string" use="required"/>
						<xs:attribute name="Namespace" type="xs:string" use="required"/>
						<xs:attribute name="FatherInclude" type="xs:string" use="required"/>
						<xs:attribute name="FatherNamespace" type="xs:string" use="required"/>
						<xs:attribute name="Constructor" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="NumberProtocol" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="RichCompare" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="TwinPointer" type="xs:string" use="required"/>
						<xs:attribute name="Delete" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="Reference" type="xs:boolean" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Module">
		<xs:annotation>
			<xs:documentation>This is the module root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
				<xs:element name="Dependencies" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Module" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Content">
					<xs:annotation>
						<xs:documentation>This element holds the content of the module</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="Feature" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represent a Feature in the modue</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Documentation of this object</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element ref="ViewProvider" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DocObject" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represnts a Document Object in the module</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0"/>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="GuiCommand" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Creats a GuiCommand in this module</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="PreferencesPage" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:annotation>
			<xs:documentation> Defines a class property</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" type="xs:string" use="required"/>
			<xs:attribute name="StartValue" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Author" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Name" type="xs:string" use="required"/>
								<xs:attribute name="EMail" type="xs:string" use="required"/>
								<xs:attribute name="Licence" type="xs:string" use="optional" default="LGPL"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DeveloperDocu" type="xs:string" minOccurs="0"/>
				<xs:element name="UserDocu" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ViewProvider">
		<xs:annotation>
			<xs:documentation>Defins a ViewProvider for a Object</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Int"/>
						<xs:enumeration value="Long"/>
						<xs:enumeration value="String"/>
						<xs:enumeration value="Object"/>
						<xs:enumeration value="Float"/>
						<xs:enumeration value="Complex"/>
						<xs:enumeration value="Char"/>
						<xs:enumeration value="Tuple"/>
						<xs:enumeration value="List"/>
						<xs:enumeration value="Dict"/>
						<xs:enumeration value="Module"/>
						<xs:enumeration value="Callable"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FreeCAD/FreeCAD/src/Mod/Material/App/UUIDsPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport
      Father="BaseClassPy"
      Name="UUIDsPy"
      PythonName="Material.UUIDs"
      Twin="ModelUUIDs"
      TwinPointer="ModelUUIDs"
      Include="Mod/Material/App/ModelUuids.h"
      Namespace="Materials"
      FatherInclude="Base/BaseClassPy.h"
      FatherNamespace="Base"
      Constructor="true"
      Delete="true">
    <Documentation>
      <Author Licence="LGPL" Name="DavidCarter" EMail="dcarter@davidcarter.ca" />
      <UserDocu>Material model UUID identifiers.</UserDocu>
    </Documentation>
    <Attribute Name="Father" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Legacy/Father</UserDocu>
      </Documentation>
      <Parameter Name="Father" Type="String"/>
    </Attribute>
    <Attribute Name="MaterialStandard" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Legacy/MaterialStandard</UserDocu>
      </Documentation>
      <Parameter Name="MaterialStandard" Type="String"/>
    </Attribute>
    <Attribute Name="Density" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Mechanical/Density</UserDocu>
      </Documentation>
      <Parameter Name="Density" Type="String"/>
    </Attribute>
    <Attribute Name="IsotropicLinearElastic" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Mechanical/IsotropicLinearElastic</UserDocu>
      </Documentation>
      <Parameter Name="IsotropicLinearElastic" Type="String"/>
    </Attribute>
    <Attribute Name="LinearElastic" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Mechanical/LinearElastic</UserDocu>
      </Documentation>
      <Parameter Name="LinearElastic" Type="String"/>
    </Attribute>
    <Attribute Name="OgdenYld2004p18" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Mechanical/OgdenYld2004p18</UserDocu>
      </Documentation>
      <Parameter Name="OgdenYld2004p18" Type="String"/>
    </Attribute>
    <Attribute Name="OrthotropicLinearElastic" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Mechanical/OrthotropicLinearElastic</UserDocu>
      </Documentation>
      <Parameter Name="OrthotropicLinearElastic" Type="String"/>
    </Attribute>
    <Attribute Name="Fluid" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Fluid/Fluid</UserDocu>
      </Documentation>
      <Parameter Name="Fluid" Type="String"/>
    </Attribute>
    <Attribute Name="Thermal" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Thermal/Thermal</UserDocu>
      </Documentation>
      <Parameter Name="Thermal" Type="String"/>
    </Attribute>
    <Attribute Name="Electromagnetic" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Electromagnetic/Electromagnetic</UserDocu>
      </Documentation>
      <Parameter Name="Electromagnetic" Type="String"/>
    </Attribute>
    <Attribute Name="Architectural" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Architectural/Architectural</UserDocu>
      </Documentation>
      <Parameter Name="Architectural" Type="String"/>
    </Attribute>
    <Attribute Name="ArchitecturalRendering" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Architectural/ArchitecturalRendering</UserDocu>
      </Documentation>
      <Parameter Name="ArchitecturalRendering" Type="String"/>
    </Attribute>
    <Attribute Name="Costs" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Costs/Costs</UserDocu>
      </Documentation>
      <Parameter Name="Costs" Type="String"/>
    </Attribute>
    <Attribute Name="BasicRendering" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/BasicRendering</UserDocu>
      </Documentation>
      <Parameter Name="BasicRendering" Type="String"/>
    </Attribute>
    <Attribute Name="TextureRendering" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/TextureRendering</UserDocu>
      </Documentation>
      <Parameter Name="TextureRendering" Type="String"/>
    </Attribute>
    <Attribute Name="AdvancedRendering" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/AdvancedRendering</UserDocu>
      </Documentation>
      <Parameter Name="AdvancedRendering" Type="String"/>
    </Attribute>
    <Attribute Name="VectorRendering" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/VectorRendering</UserDocu>
      </Documentation>
      <Parameter Name="VectorRendering" Type="String"/>
    </Attribute>
    <Attribute Name="RenderAppleseed" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderAppleseed</UserDocu>
      </Documentation>
      <Parameter Name="RenderAppleseed" Type="String"/>
    </Attribute>
    <Attribute Name="RenderCarpaint" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderCarpaint</UserDocu>
      </Documentation>
      <Parameter Name="RenderCarpaint" Type="String"/>
    </Attribute>
    <Attribute Name="RenderCycles" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderCycles</UserDocu>
      </Documentation>
      <Parameter Name="RenderCycles" Type="String"/>
    </Attribute>
    <Attribute Name="RenderDiffuse" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderDiffuse</UserDocu>
      </Documentation>
      <Parameter Name="RenderDiffuse" Type="String"/>
    </Attribute>
    <Attribute Name="RenderDisney" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderDisney</UserDocu>
      </Documentation>
      <Parameter Name="RenderDisney" Type="String"/>
    </Attribute>
    <Attribute Name="RenderEmission" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderEmission</UserDocu>
      </Documentation>
      <Parameter Name="RenderEmission" Type="String"/>
    </Attribute>
    <Attribute Name="RenderGlass" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderGlass</UserDocu>
      </Documentation>
      <Parameter Name="RenderGlass" Type="String"/>
    </Attribute>
    <Attribute Name="RenderLuxcore" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderLuxcore</UserDocu>
      </Documentation>
      <Parameter Name="RenderLuxcore" Type="String"/>
    </Attribute>
    <Attribute Name="RenderLuxrender" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderLuxrender</UserDocu>
      </Documentation>
      <Parameter Name="RenderLuxrender" Type="String"/>
    </Attribute>
    <Attribute Name="RenderMixed" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderMixed</UserDocu>
      </Documentation>
      <Parameter Name="RenderMixed" Type="String"/>
    </Attribute>
    <Attribute Name="RenderOspray" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderOspray</UserDocu>
      </Documentation>
      <Parameter Name="RenderOspray" Type="String"/>
    </Attribute>
    <Attribute Name="RenderPbrt" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderPbrt</UserDocu>
      </Documentation>
      <Parameter Name="RenderPbrt" Type="String"/>
    </Attribute>
    <Attribute Name="RenderPovray" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderPovray</UserDocu>
      </Documentation>
      <Parameter Name="RenderPovray" Type="String"/>
    </Attribute>
    <Attribute Name="RenderSubstancePBR" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderSubstancePBR</UserDocu>
      </Documentation>
      <Parameter Name="RenderSubstancePBR" Type="String"/>
    </Attribute>
    <Attribute Name="RenderTexture" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderTexture</UserDocu>
      </Documentation>
      <Parameter Name="RenderTexture" Type="String"/>
    </Attribute>
    <Attribute Name="RenderWB" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Rendering/RenderWB</UserDocu>
      </Documentation>
      <Parameter Name="RenderWB" Type="String"/>
    </Attribute>
    <Attribute Name="TestModel" ReadOnly="true">
      <Documentation>
        <UserDocu>UUID for model System:Test/Test Model</UserDocu>
      </Documentation>
      <Parameter Name="TestModel" Type="String"/>
    </Attribute>
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Base/BaseClassPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport
      Father="PyObjectBase"
      Name="BaseClassPy"
      Twin="BaseClass"
      TwinPointer="BaseClass"
      Include="Base/BaseClass.h"
      FatherInclude="Base/PyObjectBase.h"
      Namespace="Base"
      FatherNamespace="Base">
    <Documentation>
      <Author Licence="LGPL" Name="Juergen Riegel" EMail="FreeCAD@juergen-riegel.net" />
      <DeveloperDocu>This is the BaseClass class</DeveloperDocu>
      <UserDocu>This is the base class</UserDocu>
    </Documentation>
    <Methode Name="isDerivedFrom" Const="true">
      <Documentation>
        <UserDocu>Returns true if given type is a father</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="getAllDerivedFrom" Const="true">
      <Documentation>
        <UserDocu>Returns all descendants</UserDocu>
      </Documentation>
    </Methode>
    <Attribute Name="TypeId" ReadOnly="true">
      <Documentation>
        <UserDocu>Is the type of the FreeCAD object with module domain</UserDocu>
      </Documentation>
      <Parameter Name="TypeId" Type="String" />
    </Attribute>
    <Attribute Name="Module" ReadOnly="true">
      <Documentation>
        <UserDocu>Module in which this class is defined</UserDocu>
      </Documentation>
      <Parameter Name="Module" Type="String"/>
    </Attribute>
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/TechDraw/App/CenterLinePy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport
      Father="PyObjectBase"
      Name="CenterLinePy"
      Twin="CenterLine"
      TwinPointer="CenterLine"
      Include="Mod/TechDraw/App/Cosmetic.h"
      Namespace="TechDraw"
      FatherInclude="Base/PyObjectBase.h"
      FatherNamespace="Base"
      Constructor="true"
      Delete="true">
    <Documentation>
      <Author Licence="LGPL" Name="WandererFan" EMail="wandererfan@gmail.com" />
      <UserDocu>CenterLine specifies appearance parameters for TechDraw Geometry objects</UserDocu>
    </Documentation>
    <Methode Name="clone" Const="true">
        <Documentation>
            <UserDocu>Create a clone of this centerline</UserDocu>
        </Documentation>
    </Methode>
    <Methode Name="copy" Const="true">
        <Documentation>
            <UserDocu>Create a copy of this centerline</UserDocu>
        </Documentation>
    </Methode>
    <Methode Name="setFormat">
        <Documentation>
            <UserDocu>Change the appearance of this CenterLine. cl.setFormat(style, color, weight, visible)</UserDocu>
        </Documentation>
    </Methode>

    <Methode Name="getFormat">
        <Documentation>
            <UserDocu>returns the appearance attributes of this CenterLine.  returns tuple(style, color, weight, visible).</UserDocu>
        </Documentation>
    </Methode>
    <Attribute Name="Tag" ReadOnly="true">
      <Documentation>
        <UserDocu>Gives the tag of the CenterLine as string.</UserDocu>
      </Documentation>
      <Parameter Name="Tag" Type="String"/>
    </Attribute>
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/Part/App/PrecisionPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport
      Father="PyObjectBase"
      Name="PrecisionPy"
      PythonName="Part.Precision"
      Twin="Precision"
      TwinPointer="Precision"
      Include="Precision.hxx"
      Namespace="Part"
      FatherInclude="Base/PyObjectBase.h"
      FatherNamespace="Base">
    <Documentation>
      <Author Licence="LGPL" Name="Werner Mayer" EMail="wmayer@users.sourceforge.net" />
      <DeveloperDocu>This is the Type class</DeveloperDocu>
      <UserDocu>This is the Type class</UserDocu>
    </Documentation>
    <Methode Name="angular" Static="true">
      <Documentation>
        <UserDocu>Returns the recommended precision value when checking the equality of two angles (given in radians)</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="confusion" Static="true">
      <Documentation>
        <UserDocu>Returns the recommended precision value when checking coincidence of two points in real space</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="squareConfusion" Static="true">
      <Documentation>
        <UserDocu>Returns square of confusion</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="intersection" Static="true">
      <Documentation>
        <UserDocu>Returns the precision value in real space, frequently used by intersection algorithms</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="approximation" Static="true">
      <Documentation>
        <UserDocu>Returns the precision value in real space, frequently used by approximation algorithms</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="parametric" Static="true">
      <Documentation>
        <UserDocu>Convert a real space precision to a parametric space precision</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="isInfinite" Static="true">
      <Documentation>
        <UserDocu>Returns True if R may be considered as an infinite number</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="isPositiveInfinite" Static="true">
      <Documentation>
        <UserDocu>Returns True if R may  be considered as a positive infinite number</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="isNegativeInfinite" Static="true">
      <Documentation>
        <UserDocu>Returns True if R may  be considered as a negative infinite number</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="infinite" Static="true">
      <Documentation>
        <UserDocu>Returns a  big number that  can  be  considered as infinite</UserDocu>
      </Documentation>
    </Methode>
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/App/MeasureManagerPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
    <PythonExport
        Father="PyObjectBase"
        Name="MeasureManagerPy"
        Twin="MeasureManager"
        TwinPointer="MeasureManager"
        Include="App/MeasureManager.h"
        FatherInclude="Base/PyObjectBase.h"
        Namespace="App"
        Constructor="false"
        Delete="true"
        FatherNamespace="Base">
    <Documentation>
        <Author Licence="LGPL" Name="David Friedli" EMail="david@friedli-be.ch" />
        <UserDocu>MeasureManager class.

The MeasureManager handles measure types and geometry handler accross FreeCAD.</UserDocu>
        <DeveloperDocu>MeasureManager</DeveloperDocu>
    </Documentation>
        <Methode Name="addMeasureType" Static="true">
            <Documentation>
                <UserDocu>addMeasureType(id, label, measureType) -> None

Add a new measure type.

id : str
    Unique identifier of the measure type.
label : str
    Name of the module.
measureType : Measure.MeasureBasePython
    The actual measure type.</UserDocu>
            </Documentation>
        </Methode>
        <Methode Name="getMeasureTypes" Static="true" NoArgs="true">
            <Documentation>
                <UserDocu>getMeasureTypes() -> List[(id, label, pythonMeasureType)]

Returns a list of all registered measure types.</UserDocu>
            </Documentation>
        </Methode>
    </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/Part/App/ConePy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
	<PythonExport 
		Father="GeometrySurfacePy" 
		Name="ConePy" 
        PythonName="Part.Cone"
		Twin="GeomCone" 
		TwinPointer="GeomCone" 
		Include="Mod/Part/App/Geometry.h" 
		Namespace="Part" 
		FatherInclude="Mod/Part/App/GeometrySurfacePy.h" 
		FatherNamespace="Part"
		Constructor="true">
		<Documentation>
			<Author Licence="LGPL" Name="Werner Mayer" EMail="wmayer@users.sourceforge.net" />
			<UserDocu>Describes a cone in 3D space
				To create a cone there are several ways:
				Part.Cone()
				    Creates a default cone with radius 1

				Part.Cone(Cone)
				    Creates a copy of the given cone

				Part.Cone(Cone, Distance)
				    Creates a cone parallel to given cone at a certain distance

				Part.Cone(Point1,Point2,Radius1,Radius2)
				    Creates a cone defined by two points and two radii
				    The axis of the cone is the line passing through
				    Point1 and Poin2.
				    Radius1 is the radius of the section passing through
				    Point1 and Radius2 the radius of the section passing
				    through Point2.

				Part.Cone(Point1,Point2,Point3,Point4)
				    Creates a cone passing through three points Point1,
				    Point2 and Point3.
				    Its axis is defined by Point1 and Point2 and the radius of
				    its base is the distance between Point3 and its axis.
				    The distance between Point and the axis is the radius of
				    the section passing through Point4.
			</UserDocu>
		</Documentation>
		<Attribute Name="Apex" ReadOnly="true">
			<Documentation>
				<UserDocu>Compute the apex of the cone.</UserDocu>
			</Documentation>
			<Parameter Name="Apex" Type="Object"/>
		</Attribute>
		<Attribute Name="Radius" ReadOnly="false">
			<Documentation>
				<UserDocu>The radius of the cone.</UserDocu>
			</Documentation>
			<Parameter Name="Radius" Type="Float"/>
		</Attribute>
		<Attribute Name="SemiAngle" ReadOnly="false">
			<Documentation>
				<UserDocu>The semi-angle of the cone.</UserDocu>
			</Documentation>
			<Parameter Name="SemiAngle" Type="Float"/>
		</Attribute>
		<Attribute Name="Center" ReadOnly="false">
			<Documentation>
				<UserDocu>Center of the cone.</UserDocu>
			</Documentation>
			<Parameter Name="Center" Type="Object"/>
		</Attribute>
		<Attribute Name="Axis" ReadOnly="false">
			<Documentation>
				<UserDocu>The axis direction of the cone</UserDocu>
			</Documentation>
			<Parameter Name="Axis" Type="Object"/>
		</Attribute>
        <Methode Name="uIso" Const="true">
			<Documentation>
				<UserDocu>Builds the U isoparametric circle of this cone</UserDocu>
			</Documentation>
		</Methode>
        <Methode Name="vIso" Const="true">
			<Documentation>
				<UserDocu>Builds the V isoparametric circle of this cone</UserDocu>
			</Documentation>
		</Methode>
	</PythonExport>
</GenerateModel>
