=== FreeCAD/FreeCAD/src/Tools/generateBase/generateMetaModel_Module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GenerateModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="PythonExport" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Documentation" minOccurs="0"/>
							<xs:element name="Methode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation"/>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="Const" type="xs:boolean" use="optional"/>
									<xs:attribute name="Keyword" type="xs:boolean" use="optional" default="false"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Attribute" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation"/>
										<xs:element ref="Parameter"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="ReadOnly" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Sequence" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="sq_length" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_concat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_repeat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_item" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_slice" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_ass_item" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_ass_slice" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_contains" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_inplace_concat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_inplace_repeat" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="CustomAttributes" minOccurs="0"/>
							<xs:element name="ClassDeclarations" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Include" type="xs:string" use="required"/>
						<xs:attribute name="Father" type="xs:string" use="required"/>
						<xs:attribute name="Twin" type="xs:string" use="required"/>
						<xs:attribute name="Namespace" type="xs:string" use="required"/>
						<xs:attribute name="FatherInclude" type="xs:string" use="required"/>
						<xs:attribute name="FatherNamespace" type="xs:string" use="required"/>
						<xs:attribute name="Constructor" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="NumberProtocol" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="RichCompare" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="TwinPointer" type="xs:string" use="required"/>
						<xs:attribute name="Delete" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="Reference" type="xs:boolean" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Module">
		<xs:annotation>
			<xs:documentation>This is the module root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
				<xs:element name="Dependencies" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Module" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Content">
					<xs:annotation>
						<xs:documentation>This element holds the content of the module</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="Feature" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represent a Feature in the modue</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Documentation of this object</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element ref="ViewProvider" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DocObject" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represnts a Document Object in the module</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0"/>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="GuiCommand" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Creats a GuiCommand in this module</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="PreferencesPage" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:annotation>
			<xs:documentation> Defines a class property</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" type="xs:string" use="required"/>
			<xs:attribute name="StartValue" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Author" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Name" type="xs:string" use="required"/>
								<xs:attribute name="EMail" type="xs:string" use="required"/>
								<xs:attribute name="Licence" type="xs:string" use="optional" default="LGPL"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DeveloperDocu" type="xs:string" minOccurs="0"/>
				<xs:element name="UserDocu" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ViewProvider">
		<xs:annotation>
			<xs:documentation>Defins a ViewProvider for a Object</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Int"/>
						<xs:enumeration value="Long"/>
						<xs:enumeration value="String"/>
						<xs:enumeration value="Object"/>
						<xs:enumeration value="Float"/>
						<xs:enumeration value="Complex"/>
						<xs:enumeration value="Char"/>
						<xs:enumeration value="Tuple"/>
						<xs:enumeration value="List"/>
						<xs:enumeration value="Dict"/>
						<xs:enumeration value="Module"/>
						<xs:enumeration value="Callable"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FreeCAD/FreeCAD/src/App/DocumentPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport 
    Father="PropertyContainerPy" 
    Name="DocumentPy" 
    Twin="Document" 
    TwinPointer="Document" 
    Include="App/Document.h" 
    Namespace="App" 
    FatherInclude="App/PropertyContainerPy.h" 
    FatherNamespace="App">
    <Documentation>
      <Author Licence="LGPL" Name="Juergen Riegel" EMail="FreeCAD@juergen-riegel.net" />
      <UserDocu>This is a Document class</UserDocu>
    </Documentation>
    <Methode Name="save">
      <Documentation>
        <UserDocu>Save the document to disk</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="saveAs">
      <Documentation>
        <UserDocu>Save the document under a new name to disk</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="saveCopy">
      <Documentation>
        <UserDocu>Save a copy of the document under a new name to disk</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="load">
      <Documentation>
        <UserDocu>Load the document from the given path</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="restore">
      <Documentation>
        <UserDocu>Restore the document from disk</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="mergeProject">
      <Documentation>
        <UserDocu>Merges this document with another project file</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="exportGraphviz">
      <Documentation>
        <UserDocu>Export the dependencies of the objects as graph</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="openTransaction">
      <Documentation>
        <UserDocu>Open a new Undo/Redo transaction.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="abortTransaction">
      <Documentation>
        <UserDocu>Abort an Undo/Redo transaction (rollback)</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="commitTransaction">
      <Documentation>
        <UserDocu>Commit an Undo/Redo transaction</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="addObject" Keyword="true">
      <Documentation>
          <UserDocu>addObject(type, name=None, objProxy=None, viewProxy=None, attach=False, viewType=None)

Add an object to document

type (String): the type of the document object to create.
name (String): the optional name of the new object.
objProxy (Object): the Python binding object to attach to the new document object.
viewProxy (Object): the Python binding object to attach the view provider of this object.
attach (Boolean): if True, then bind the document object first before adding to the document
        to allow Python code to override view provider type. Once bound, and before adding to
        the document, it will try to call Python binding object's attach(obj) method.
viewType (String): override the view provider type directly, only effective when attach is False.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="removeObject">
      <Documentation>
        <UserDocu>Remove an object from the document</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="copyObject">
      <Documentation>
        <UserDocu>copyObject(object, bool with_dependencies = False, bool ignored_argument = False)
        Copy an object from another document to this document. If with_dependencies is True, all objects this object depends on are copied too.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="moveObject">
      <Documentation>
        <UserDocu>moveObject(object, bool with_dependencies = False)
        Transfers an object from another document to this document. If with_dependencies is True, all objects this object depends on are transferred too.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="undo">
      <Documentation>
        <UserDocu>Undo one transaction</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="redo">
      <Documentation>
        <UserDocu>Redo a previously undone transaction</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="clearUndos">
      <Documentation>
        <UserDocu>Clear the undo stack of the document</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="recompute">
      <Documentation>
        <UserDocu>Recompute the document and returns the amount of recomputed features</UserDocu>
      </Documentation>
    </Methode>
	<Methode Name="getObject">
		<Documentation>
			<UserDocu>Return the object with the given name</UserDocu>
		</Documentation>
	</Methode>
	<Methode Name="getObjectsByLabel">
		<Documentation>
			<UserDocu>Return the objects with the given label name.
NOTE: It's possible that several objects have the same label name.</UserDocu>
		</Documentation>
	</Methode>
	<Methode Name="findObjects">
		<Documentation>
			<UserDocu>findObjects([string (type)], [string (name)]) -&gt; list
Return a list of objects that match the specified type and name.
Both parameters are optional.</UserDocu>
		</Documentation>
	</Methode>
    <Methode Name="getLinksTo">
        <Documentation>
            <UserDocu>
                getLinksTo(obj, options=0, maxCount=0): return objects linked to 'obj'

                options: 1: recursive, 2: check link array. Options can combine.
                maxCount: to limit the number of links returned
            </UserDocu>
        </Documentation>
    </Methode>
	  <Methode Name="supportedTypes">
		  <Documentation>
			  <UserDocu>A list of supported types of objects</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="getTempFileName">
		  <Documentation>
			  <UserDocu>Returns a file name with path in the temp directory of the document.</UserDocu>
		  </Documentation>
	  </Methode>
	  <Attribute Name="DependencyGraph" ReadOnly="true">
		<Documentation>
			<UserDocu>The dependency graph as GraphViz text</UserDocu>
		</Documentation>
		<Parameter Name="DependencyGraph" Type="String" />
	</Attribute>
	  <Attribute Name="ActiveObject" ReadOnly="true">
		  <Documentation>
			  <UserDocu>The active object of the document</UserDocu>
		  </Documentation>
		  <Parameter Name="ActiveObject" Type="Object" />
	  </Attribute>
	  <Attribute Name="Objects" ReadOnly="true">
      <Documentation>
        <UserDocu>The list of object handled by this document</UserDocu>
      </Documentation>
      <Parameter Name="Objects" Type="List" />
    </Attribute>
    <Attribute Name="TopologicalSortedObjects" ReadOnly="true">
      <Documentation>
        <UserDocu>The list of object of this document in topological sorted order</UserDocu>
      </Documentation>
      <Parameter Name="ToplogicalSortedObjects" Type="List" />
    </Attribute>
    <Attribute Name="RootObjects" ReadOnly="true">
      <Documentation>
        <UserDocu>The list of root object of this document</UserDocu>
      </Documentation>
      <Parameter Name="RootObjects" Type="List" />
    </Attribute>
    <Attribute Name="UndoMode" ReadOnly="false">
      <Documentation>
        <UserDocu>The Undo mode of the Document (0 = no Undo, 1 = Undo/Redo)</UserDocu>
      </Documentation>
      <Parameter Name="UndoMode" Type="Int" />
    </Attribute>
    <Attribute Name="UndoRedoMemSize" ReadOnly="true">
      <Documentation>
        <UserDocu>The size of the Undo stack in byte</UserDocu>
      </Documentation>
      <Parameter Name="UndoRedoMemSize" Type="Int" />
    </Attribute>
    <Attribute Name="UndoCount" ReadOnly="true">
      <Documentation>
        <UserDocu>Number of possible Undos</UserDocu>
      </Documentation>
      <Parameter Name="UndoCount" Type="Int" />
    </Attribute>
    <Attribute Name="RedoCount" ReadOnly="true">
      <Documentation>
        <UserDocu>Number of possible Redos</UserDocu>
      </Documentation>
      <Parameter Name="RedoCount" Type="Int"/>
    </Attribute>
    <Attribute Name="UndoNames" ReadOnly="true">
      <Documentation>
        <UserDocu>A list of Undo names</UserDocu>
      </Documentation>
      <Parameter Name="UndoNames" Type="List"/>
    </Attribute>
    <Attribute Name="RedoNames" ReadOnly="true">
      <Documentation>
        <UserDocu>A List of Redo names</UserDocu>
      </Documentation>
      <Parameter Name="RedoNames" Type="List"/>
    </Attribute>
    <Attribute Name="Name" ReadOnly="true">
      <Documentation>
        <UserDocu>The internal name of the document</UserDocu>
      </Documentation>
      <Parameter Name="Name" Type="String"/>
    </Attribute>
    <Attribute Name="RecomputesFrozen">
      <Documentation>
        <UserDocu>Returns or sets if automatic recomputes for this document are disabled.</UserDocu>
      </Documentation>
      <Parameter Name="RecomputesFrozen" Type="Boolean"/>
    </Attribute>
    <CustomAttributes />
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/Part/App/ShapeFix/ShapeFix_EdgePy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport
      Father="PyObjectBase"
      Name="ShapeFix_EdgePy"
      PythonName="Part.ShapeFix.Edge"
      Twin="ShapeFix_Edge"
      TwinPointer="ShapeFix_Edge"
      Include="ShapeFix_Edge.hxx"
      Namespace="Part"
      FatherInclude="Base/PyObjectBase.h"
      FatherNamespace="Base"
      Constructor="true"
      Delete="false">
    <Documentation>
      <Author Licence="LGPL" Name="Werner Mayer" EMail="wmayer@users.sourceforge.net" />
      <UserDocu>Fixing invalid edge</UserDocu>
    </Documentation>
    <Methode Name="fixRemovePCurve">
      <Documentation>
        <UserDocu>Removes pcurve(s) if not matching vertices.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="fixRemoveCurve3d">
      <Documentation>
        <UserDocu>Removes 3d curve if not matching vertices.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="fixAddPCurve">
      <Documentation>
        <UserDocu>Adds missing pcurve(s) by projecting 3d curve.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="fixAddCurve3d">
      <Documentation>
        <UserDocu>Tries to build missing 3d curve.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="fixVertexTolerance">
      <Documentation>
        <UserDocu>Increases tolerances of edge vertices.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="fixReversed2d">
      <Documentation>
        <UserDocu>Fixes edge if pcurve is opposite to 3d curve.</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="fixSameParameter">
      <Documentation>
        <UserDocu>Makes edge SameParameter and sets tolerance.</UserDocu>
      </Documentation>
    </Methode>
    <ClassDeclarations>
private:
    Handle(ShapeFix_Edge) hEdge;

public:
    void setHandle(Handle(ShapeFix_Edge) handle) {
        setTwinPointer(handle.get());
        hEdge = handle;
    }
    </ClassDeclarations>
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/Part/App/TopoShapeEdgePy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport 
      Father="TopoShapePy" 
      Name="TopoShapeEdgePy" 
      Twin="TopoShape" 
      TwinPointer="TopoShape" 
      Include="Mod/Part/App/TopoShape.h" 
      Namespace="Part" 
      FatherInclude="Mod/Part/App/TopoShapePy.h" 
      FatherNamespace="Part"
      Constructor="true">
    <Documentation>
      <Author Licence="LGPL" Name="Juergen Riegel" EMail="Juergen.Riegel@web.de" />
      <UserDocu>TopoShapeEdge is the OpenCasCade topological edge wrapper</UserDocu>
    </Documentation>
		<Methode Name="getParameterByLength" Const="true">
			<Documentation>
				<UserDocu>float = getParameterByLength(float) - Return parameter [First,Last]. Input value must be of [0|Length]</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="tangentAt" Const="true">
		  <Documentation>
			  <UserDocu>Vector = tangentAt(pos) - Get the tangent at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="valueAt" Const="true">
		  <Documentation>
			  <UserDocu>Vector = valueAt(pos) - Get the point at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
		<Methode Name="parameterAt" Const="true">
			<Documentation>
				<UserDocu>Float = parameterAt(Vertex) - Get the parameter at the given vertex if lying on the edge</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="normalAt" Const="true">
		  <Documentation>
			  <UserDocu>Vector = normalAt(pos) - Get the normal vector at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="derivative1At" Const="true">
		  <Documentation>
			  <UserDocu>Vector = d1At(pos) - Get the first derivative at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="derivative2At" Const="true">
		  <Documentation>
			  <UserDocu>Vector = d2At(pos) - Get the second derivative at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="derivative3At" Const="true">
		  <Documentation>
			  <UserDocu>Vector = d3At(pos) - Get the third derivative at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="curvatureAt" Const="true">
		  <Documentation>
			  <UserDocu>Float = curvatureAt(pos) - Get the curvature at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="centerOfCurvatureAt" Const="true">
		  <Documentation>
			  <UserDocu>Vector = centerOfCurvatureAt(float pos) - Get the center of curvature at the given parameter [First|Last] if defined</UserDocu>
		  </Documentation>
	  </Methode>
		<Methode Name="setTolerance">
			<Documentation>
				<UserDocu>Set the tolerance for the edge.</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="discretize" Const="true" Keyword="true">
			<Documentation>
        <UserDocu>Discretizes the edge and returns a list of points.
The function accepts keywords as argument:
discretize(Number=n) => gives a list of 'n' equidistant points
discretize(QuasiNumber=n) => gives a list of 'n' quasi equidistant points (is faster than the method above)
discretize(Distance=d) => gives a list of equidistant points with distance 'd'
discretize(Deflection=d) => gives a list of points with a maximum deflection 'd' to the edge
discretize(QuasiDeflection=d) => gives a list of points with a maximum deflection 'd' to the edge (faster)
discretize(Angular=a,Curvature=c,[Minimum=m]) => gives a list of points with an angular deflection of 'a'
                                    and a curvature deflection of 'c'. Optionally a minimum number of points
                                    can be set which by default is set to 2.

Optionally you can set the keywords 'First' and 'Last' to define a sub-range of the parameter range
of the edge.

If no keyword is given then it depends on whether the argument is an int or float.
If it's an int then the behaviour is as if using the keyword 'Number', if it's float
then the behaviour is as if using the keyword 'Distance'.

Example:

import Part
e=Part.makeCircle(5)
p=e.discretize(Number=50,First=3.14)
s=Part.Compound([Part.Vertex(i) for i in p])
Part.show(s)


p=e.discretize(Angular=0.09,Curvature=0.01,Last=3.14,Minimum=100)
s=Part.Compound([Part.Vertex(i) for i in p])
Part.show(s)
</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="split">
			<Documentation>
				<UserDocu>Splits the edge at the given parameter values and builds a wire out of it</UserDocu>
			</Documentation>
		</Methode>
		<Attribute Name="Tolerance">
			<Documentation>
				<UserDocu>Set or get the tolerance of the vertex</UserDocu>
			</Documentation>
			<Parameter Name="Tolerance" Type="Float"/>
		</Attribute>
		<Attribute Name="Length" ReadOnly="true">
		  <Documentation>
			  <UserDocu>Returns the length of the edge</UserDocu>
		  </Documentation>
		  <Parameter Name="Length" Type="Float"/>
	  </Attribute>
	  <Attribute Name="ParameterRange" ReadOnly="true">
		  <Documentation>
			  <UserDocu>Returns a 2 tuple with the parameter range</UserDocu>
		  </Documentation>
		  <Parameter Name="ParameterRange" Type="Tuple"/>
	  </Attribute>
		<Attribute Name="FirstParameter" ReadOnly="true">
			<Documentation>
				<UserDocu>Returns the start value of the parameter range</UserDocu>
			</Documentation>
			<Parameter Name="FirstParameter" Type="Float"/>
		</Attribute>
		<Attribute Name="LastParameter" ReadOnly="true">
			<Documentation>
				<UserDocu>Returns the end value of the parameter range</UserDocu>
			</Documentation>
			<Parameter Name="LastParameter" Type="Float"/>
		</Attribute>
		<Attribute Name="Curve" ReadOnly="true">
		  <Documentation>
			  <UserDocu>Returns the 3D curve of the edge</UserDocu>
		  </Documentation>
		  <Parameter Name="Curve" Type="Object"/>
	  </Attribute>
	  <Attribute Name="CenterOfMass" ReadOnly="true">
      <Documentation>
        <UserDocu>Returns the center of mass of the current system.
If the gravitational field is uniform, it is the center of gravity.
The coordinates returned for the center of mass are expressed in the
absolute Cartesian coordinate system.</UserDocu>
      </Documentation>
      <Parameter Name="CenterOfMass" Type="Object"/>
    </Attribute>
	<Attribute Name="Closed" ReadOnly="true">
		<Documentation>
			<UserDocu>Returns true of the edge is closed</UserDocu>
		</Documentation>
		<Parameter Name="Closed" Type="Boolean"/>
	</Attribute>
	  <Attribute Name="Degenerated" ReadOnly="true">
		  <Documentation>
			  <UserDocu>Returns true of the edge is degenerated</UserDocu>
		  </Documentation>
		  <Parameter Name="Degenerated" Type="Boolean"/>
	  </Attribute>
		<ClassDeclarations>
		</ClassDeclarations>
	</PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Gui/ViewProviderDocumentObjectPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
	<PythonExport 
		Father="ViewProviderPy" 
		Name="ViewProviderDocumentObjectPy" 
		Twin="ViewProviderDocumentObject" 
		TwinPointer="ViewProviderDocumentObject" 
		Include="Gui/ViewProviderDocumentObject.h" 
		Namespace="Gui" 
		FatherInclude="Gui/ViewProviderPy.h"
		FatherNamespace="Gui">
		<Documentation>
			<Author Licence="LGPL" Name="Werner Mayer" EMail="wmayer@users.sourceforge.net" />
			<UserDocu>This is the ViewProvider base class</UserDocu>
		</Documentation>
		<Methode Name="update">
			<Documentation>
				<UserDocu>Update the view representation of the object</UserDocu>
			</Documentation>
		</Methode>
		<Attribute Name="Object" ReadOnly="true">
			<Documentation>
				<UserDocu>Return the associated data object</UserDocu>
			</Documentation>
			<Parameter Name="Object" Type="Object" />
		</Attribute>
	</PythonExport>
</GenerateModel>
