=== FreeCAD/FreeCAD/src/Tools/generateBase/generateMetaModel_Module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von Juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<!-- Mit XMLSpy v2006 rel. 3 U bearbeitet (http://www.altova.com) von juergen Riegel (DCX) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GenerateModel">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="PythonExport" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="Documentation" minOccurs="0"/>
							<xs:element name="Methode" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation"/>
										<xs:element ref="Parameter" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="Const" type="xs:boolean" use="optional"/>
									<xs:attribute name="Keyword" type="xs:boolean" use="optional" default="false"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Attribute" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation"/>
										<xs:element ref="Parameter"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
									<xs:attribute name="ReadOnly" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="Sequence" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute name="sq_length" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_concat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_repeat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_item" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_slice" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_ass_item" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_ass_slice" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_contains" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_inplace_concat" type="xs:boolean" use="required"/>
									<xs:attribute name="sq_inplace_repeat" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="CustomAttributes" minOccurs="0"/>
							<xs:element name="ClassDeclarations" type="xs:string"/>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required"/>
						<xs:attribute name="Include" type="xs:string" use="required"/>
						<xs:attribute name="Father" type="xs:string" use="required"/>
						<xs:attribute name="Twin" type="xs:string" use="required"/>
						<xs:attribute name="Namespace" type="xs:string" use="required"/>
						<xs:attribute name="FatherInclude" type="xs:string" use="required"/>
						<xs:attribute name="FatherNamespace" type="xs:string" use="required"/>
						<xs:attribute name="Constructor" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="NumberProtocol" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="RichCompare" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="TwinPointer" type="xs:string" use="required"/>
						<xs:attribute name="Delete" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="Reference" type="xs:boolean" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Module">
		<xs:annotation>
			<xs:documentation>This is the module root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
				<xs:element name="Dependencies" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Module" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Content">
					<xs:annotation>
						<xs:documentation>This element holds the content of the module</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Property" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="Feature" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represent a Feature in the modue</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Documentation of this object</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element ref="ViewProvider" minOccurs="0"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="DocObject" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Represnts a Document Object in the module</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="Documentation" minOccurs="0"/>
										<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="GuiCommand" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Creats a GuiCommand in this module</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="PreferencesPage" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Property">
		<xs:annotation>
			<xs:documentation> Defines a class property</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" type="xs:string" use="required"/>
			<xs:attribute name="StartValue" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentation">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Author" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="Name" type="xs:string" use="required"/>
								<xs:attribute name="EMail" type="xs:string" use="required"/>
								<xs:attribute name="Licence" type="xs:string" use="optional" default="LGPL"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="DeveloperDocu" type="xs:string" minOccurs="0"/>
				<xs:element name="UserDocu" type="xs:string" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ViewProvider">
		<xs:annotation>
			<xs:documentation>Defins a ViewProvider for a Object</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Property" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Parameter">
		<xs:complexType>
			<xs:attribute name="Name" type="xs:string" use="required"/>
			<xs:attribute name="Type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Int"/>
						<xs:enumeration value="Long"/>
						<xs:enumeration value="String"/>
						<xs:enumeration value="Object"/>
						<xs:enumeration value="Float"/>
						<xs:enumeration value="Complex"/>
						<xs:enumeration value="Char"/>
						<xs:enumeration value="Tuple"/>
						<xs:enumeration value="List"/>
						<xs:enumeration value="Dict"/>
						<xs:enumeration value="Module"/>
						<xs:enumeration value="Callable"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FreeCAD/FreeCAD/src/Mod/Robot/App/RobotObjectPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport 
    Father="DocumentObjectPy"  
    Name="RobotObjectPy" 
    Twin="RobotObject" 
    TwinPointer="RobotObject" 
    Include="Mod/Robot/App/RobotObject.h" 
    Namespace="Robot" 
    FatherInclude="App/DocumentObjectPy.h" 
    FatherNamespace="App">
    <Documentation>
      <Author Licence="LGPL" Name="Juergen Riegel" EMail="FreeCAD@juergen-riegel.net" />
      <UserDocu>Robot document object</UserDocu>
    </Documentation>
	<Methode Name="getRobot">
		<Documentation>
			<UserDocu>
					Returns a copy of the robot. Be aware, the robot behaves the same
					like the robot of the object but is a copy!
			</UserDocu>
		</Documentation>
	</Methode>

  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Base/CoordinateSystemPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport 
      Father="PyObjectBase" 
      Name="CoordinateSystemPy" 
      Twin="CoordinateSystem" 
      TwinPointer="CoordinateSystem" 
      Include="Base/CoordinateSystem.h" 
      FatherInclude="Base/PyObjectBase.h" 
      Namespace="Base" 
      Constructor="true"
      Delete="true" 
      FatherNamespace="Base">
    <Documentation>
      <Author Licence="LGPL" Name="Juergen Riegel" EMail="FreeCAD@juergen-riegel.net" />
      <DeveloperDocu>This is the CoordinateSystem export class</DeveloperDocu>
      <UserDocu>Base.CoordinateSystem class.\n
An orthonormal right-handed coordinate system in 3D space.\n
CoordinateSystem()
Empty constructor.</UserDocu>
    </Documentation>
    <Methode Name="setAxes">
      <Documentation>
        <UserDocu>setAxes(axis, xDir) -> None\n
Set axis or Z-direction, and X-direction.
The X-direction is determined from the orthonormal compononent of `xDir`
with respect to `axis` direction.\n
axis : Base.Axis, Base.Vector
xDir : Base.Vector</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="displacement" Const="true">
      <Documentation>
        <UserDocu>displacement(coordSystem2) -> Base.Placement\n
Computes the placement from this to the passed coordinate system `coordSystem2`.\n
coordSystem2 : Base.CoordinateSystem</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="transformTo">
      <Documentation>
        <UserDocu>transformTo(vector) -> Base.Vector\n
Computes the coordinates of the point in coordinates of this coordinate system.\n
vector : Base.Vector</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="transform">
      <Documentation>
        <UserDocu>transform(trans) -> None\n
Applies a transformation on this coordinate system.\n
trans : Base.Rotation, Base.Placement</UserDocu>
      </Documentation>
    </Methode>
    <Methode Name="setPlacement">
      <Documentation>
        <UserDocu>setPlacment(placement) -> None\n
Set placement to the coordinate system.\n
placement : Base.Placement</UserDocu>
      </Documentation>
    </Methode>
    <Attribute Name="Axis" ReadOnly="false">
      <Documentation>
        <UserDocu>Set or get axis.</UserDocu>
      </Documentation>
      <Parameter Name="Axis" Type="Object" />
    </Attribute>
    <Attribute Name="XDirection" ReadOnly="false">
      <Documentation>
        <UserDocu>Set or get X-direction.</UserDocu>
      </Documentation>
      <Parameter Name="XDirection" Type="Object" />
    </Attribute>
    <Attribute Name="YDirection" ReadOnly="false">
      <Documentation>
        <UserDocu>Set or get Y-direction.</UserDocu>
      </Documentation>
      <Parameter Name="YDirection" Type="Object" />
    </Attribute>
    <Attribute Name="ZDirection" ReadOnly="false">
      <Documentation>
        <UserDocu>Set or get Z-direction.</UserDocu>
        </Documentation>
        <Parameter Name="ZDirection" Type="Object" />
    </Attribute>
    <Attribute Name="Position" ReadOnly="false">
      <Documentation>
        <UserDocu>Set or get position.</UserDocu>
      </Documentation>
      <Parameter Name="Position" Type="Object" />
    </Attribute>
  </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/Mesh/App/FacetPy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
  <PythonExport 
      Father="PyObjectBase" 
      Name="FacetPy" 
      Twin="Facet" 
      TwinPointer="Facet" 
      Include="Mod/Mesh/App/Facet.h" 
      FatherInclude="Base/PyObjectBase.h" 
      Namespace="Mesh" 
      Constructor="true"
      Delete="true"
      FatherNamespace="Base">
    <Documentation>
      <Author Licence="LGPL" Name="Juergen Riegel" EMail="Juergen.Riegel@web.de" />
		<DeveloperDocu>Facet in a Mesh</DeveloperDocu>
		<UserDocu>Facet in mesh
This is a facet in a MeshObject. You can get it by e.g. iterating a
mesh. The facet has a connection to its mesh and allows therefore
topological operations. It is also possible to create an unbounded facet e.g. to create
a mesh. In this case the topological operations will fail. The same is
when you cut the bound to the mesh by calling unbound().
		</UserDocu>
	</Documentation>
	  <Methode Name="unbound">
		  <Documentation>
			  <UserDocu>method unbound()
Cut the connection to a MeshObject. The facet becomes
free and is more or less a simple facet.
After calling unbound() no topological operation will
work!
			  </UserDocu>
		  </Documentation>
	  </Methode>
	  <Methode Name="intersect">
		  <Documentation>
			  <UserDocu>intersect(Facet) -> list 
Get a list of intersection points with another triangle.
			  </UserDocu>
		  </Documentation>
	  </Methode>
      <Methode Name="isDegenerated">
          <Documentation>
              <UserDocu>isDegenerated([float]) -> boolean
Returns true if the facet is degenerated, otherwise false.
              </UserDocu>
          </Documentation>
      </Methode>
      <Methode Name="isDeformed">
          <Documentation>
              <UserDocu>isDegenerated(MinAngle, MaxAngle) -> boolean
Returns true if the facet is deformed, otherwise false.
A triangle is considered deformed if an angle is less than MinAngle
or higher than MaxAngle.
The two angles are given in radian.
              </UserDocu>
          </Documentation>
      </Methode>
      <Methode Name="getEdge">
          <Documentation>
              <UserDocu>getEdge(int) -> Edge
Returns the edge of the facet.
              </UserDocu>
          </Documentation>
      </Methode>
      <Attribute Name="Index" ReadOnly="true">
		  <Documentation>
			  <UserDocu>The index of this facet in the MeshObject</UserDocu>
		  </Documentation>
		  <Parameter Name="Index" Type="Long"/>
	  </Attribute>
	  <Attribute Name="Bound" ReadOnly="true">
		  <Documentation>
			  <UserDocu>Bound state of the facet</UserDocu>
		  </Documentation>
		  <Parameter Name="Bound" Type="Boolean"/>
	  </Attribute>
	  <Attribute Name="Normal" ReadOnly="true">
		  <Documentation>
			  <UserDocu>Normal vector of the facet.</UserDocu>
		  </Documentation>
		  <Parameter Name="Normal" Type="Object"/>
	  </Attribute>
	  <Attribute Name="Points" ReadOnly="true">
		  <Documentation>
			  <UserDocu>A list of points of the facet</UserDocu>
		  </Documentation>
		  <Parameter Name="Points" Type="List"/>
	  </Attribute>
	  <Attribute Name="PointIndices" ReadOnly="true">
		  <Documentation>
			  <UserDocu>The index tuple of point vertices of the mesh this facet is built of</UserDocu>
		  </Documentation>
		  <Parameter Name="PointIndices" Type="Tuple"/>
	  </Attribute>
		<Attribute Name="NeighbourIndices" ReadOnly="true">
			<Documentation>
				<UserDocu>The index tuple of neighbour facets of the mesh this facet is adjacent with</UserDocu>
			</Documentation>
			<Parameter Name="NeighbourIndices" Type="Tuple"/>
		</Attribute>
        <Attribute Name="Area" ReadOnly="true">
            <Documentation>
                <UserDocu>The area of the facet</UserDocu>
            </Documentation>
            <Parameter Name="Area" Type="Float"/>
        </Attribute>
        <Attribute Name="AspectRatio" ReadOnly="true">
            <Documentation>
                <UserDocu>The aspect ratio of the facet computed by longest edge and its height</UserDocu>
            </Documentation>
            <Parameter Name="AspectRatio" Type="Float"/>
        </Attribute>
        <Attribute Name="AspectRatio2" ReadOnly="true">
            <Documentation>
                <UserDocu>The aspect ratio of the facet computed by radius of circum-circle and in-circle</UserDocu>
            </Documentation>
            <Parameter Name="AspectRatio2" Type="Float"/>
        </Attribute>
        <Attribute Name="Roundness" ReadOnly="true">
            <Documentation>
                <UserDocu>The roundness of the facet</UserDocu>
            </Documentation>
            <Parameter Name="Roundness" Type="Float"/>
        </Attribute>
        <Attribute Name="CircumCircle" ReadOnly="true">
            <Documentation>
                <UserDocu>The center and radius of the circum-circle</UserDocu>
            </Documentation>
            <Parameter Name="CircumCircle" Type="Tuple"/>
        </Attribute>
        <Attribute Name="InCircle" ReadOnly="true">
            <Documentation>
                <UserDocu>The center and radius of the in-circle</UserDocu>
            </Documentation>
            <Parameter Name="InCircle" Type="Tuple"/>
        </Attribute>
    </PythonExport>
</GenerateModel>

=== FreeCAD/FreeCAD/src/Mod/Part/App/GeometrySurfacePy.xml
<?xml version="1.0" encoding="UTF-8"?>
<GenerateModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="generateMetaModel_Module.xsd">
	<PythonExport
		Father="GeometryPy"
		Name="GeometrySurfacePy"
		Twin="GeomSurface"
		TwinPointer="GeomSurface"
		Include="Mod/Part/App/Geometry.h"
		Namespace="Part"
		FatherInclude="Mod/Part/App/GeometryPy.h"
		FatherNamespace="Part"
		Constructor="true">
		<Documentation>
			<Author Licence="LGPL" Name="Werner Mayer" EMail="wmayer@users.sourceforge.net" />
			<UserDocu>
				The abstract class GeometrySurface is the root class of all surface objects.
			</UserDocu>
		</Documentation>
		<Methode Name="toShape" Const="true">
			<Documentation>
				<UserDocu>Return the shape for the geometry.</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="value">
			<Documentation>
				<UserDocu>Computes the point of parameter (u,v) on this surface</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="tangent">
			<Documentation>
				<UserDocu>Computes the tangent of parameter (u,v) on this geometry</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="bounds">
			<Documentation>
				<UserDocu>
					Returns the parametric bounds (U1, U2, V1, V2) of this trimmed surface.
				</UserDocu>
			</Documentation>
		</Methode>
		<Attribute Name="Continuity" ReadOnly="true">
			<Documentation>
				<UserDocu>
					Returns the global continuity of the surface.
				</UserDocu>
			</Documentation>
			<Parameter Name="Continuity" Type="String"/>
		</Attribute>
		<Methode Name="isUPeriodic">
			<Documentation>
				<UserDocu>Returns true if this patch is periodic in the given parametric direction.</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="isVPeriodic">
			<Documentation>
				<UserDocu>Returns true if this patch is periodic in the given parametric direction.</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="isUClosed">
			<Documentation>
				<UserDocu>
					Checks if this surface is closed in the u parametric direction.
				</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="isVClosed">
			<Documentation>
				<UserDocu>
					Checks if this surface is closed in the v parametric direction.
				</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="UPeriod">
			<Documentation>
				<UserDocu>
					Returns the period of this patch in the u parametric direction.
				</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="VPeriod">
			<Documentation>
				<UserDocu>
					Returns the period of this patch in the v parametric direction.
				</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="parameter">
			<Documentation>
				<UserDocu>Returns the parameter on the curve
of the nearest orthogonal projection of the point.</UserDocu>
			</Documentation>
		</Methode>
		<Methode Name="toBSpline">
			<Documentation>
				<UserDocu>
					Returns a B-Spline representation of this surface. 
The required arguments are:
* tolerance
* continuity in u (as string e.g. C0, G0, G1, C1, G2, C3, CN)
* continuity in v (as string e.g. C0, G0, G1, C1, G2, C3, CN)
* maximum degree in u
* maximum degree in v
* maximum number of segments
* precision code (optional, default=0)
				</UserDocu>
			</Documentation>
		</Methode>
	</PythonExport>
</GenerateModel>
